openai:
  api_key: ${OPENAI_API_KEY:}

google_cloud:
  api_key_file_path: ${GOOGLE_APPLICATION_CREDENTIALS:/Users/jonathan/Documents/BarIlan/chat_bot_repo/chat_bot_server/keys/qualified-root-410910-4b648be28622.json}
