openai:
  api_key: ${OPENAI_API_KEY:}

google_cloud:
  api_key_file_path: ${GOOGLE_APPLICATION_CREDENTIALS:/Users/jonathan/Documents/GitHub/chat_bot_repo/chat_bot_server/qualified-root-410910-72d5afabffb3.json}
